[workspace]
members = [
    "crates/core",
    "crates/config",
    "crates/ocr",
    "crates/clipboard",
    "crates/memo",
    "crates/keys",
    "crates/canvas",
    "crates/tauri",
]
resolver = "2"

[workspace.package]
version = "0.0.3"
authors = ["MemoPaws"]
edition = "2021"
homepage = "https://github.com/Zomcxj/MemoPaws"
